---
title: "Get line counts for the 100LC corpora"
author: "Steven Moran"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  github_document:
  pandoc_args: --webtex
---

```{r warning=FALSE, message=FALSE}
library(dplyr)
library(tidyr)
library(knitr)
```

```{r}
# For development, use the test database
# load('../../../100LC-dev/Database/test.Rdata')

# For production, load the R serialized version of the 100 LC database
load('../../../100LC-dev/Database/100LC.Rdata')

# Remove all NAs (NULLs) in the line.text field in the database, i.e. any empty lines
df <- df %>% filter(!is.na(text))
```

```{r}
# Read in Olga's report (Python script's output)
report <- read.csv('line_counts.csv')
```

```{r}
# Calculate counts from database
## Totals
total.files <- df %>% select(name, file_id) %>% distinct() %>% group_by(name) %>% summarize(db_total_files = n())
total.lines <- df %>% select(name, line_id) %>% distinct() %>% group_by(name) %>% summarize(db_total_lines = n())

## Genre specific
genre.broad.files <- df %>% select(name, file_id, genre_broad) %>% distinct() %>% group_by(name, genre_broad) %>% summarize(db_fiction_files = n())
genre.broad.lines <- df %>% select(name, line_id, genre_broad) %>% distinct() %>% group_by(name, genre_broad) %>% summarize(db_total_files = n())

## Convert output of genres to wide format for merging
genre.broad.files.wide <- spread(genre.broad.files, key = genre_broad, value = db_fiction_files)
genre.broad.lines.wide <- spread(genre.broad.lines, key = genre_broad, value = db_total_files)

# Rename the columns
genre.broad.files.wide <- genre.broad.files.wide %>% rename(db_conversation_files = conversation, db_fiction_files = fiction, db_grammar_files = grammar, db_non_fiction_files ='non-fiction', db_professional_files = professional)
genre.broad.lines.wide <- genre.broad.lines.wide %>% rename(db_conversation_lines = conversation, db_fiction_lines = fiction, db_grammar_lines = grammar, db_non_fiction_lines ='non-fiction', db_professional_lines = professional)


# Combine the data frames
db.report <- left_join(total.files, total.lines)
db.report <- left_join(db.report, genre.broad.files.wide)
db.report <- left_join(db.report, genre.broad.lines.wide)
```

```{r}
# Compare the Python vs database reports
## Combine them
combined.reports <- left_join(report, db.report, by=c('language'='name'))
combined.reports$delta_total_lines <- abs(combined.reports$total_lines-combined.reports$db_total_lines)

## Reorder to make it easier to compare
combined.reports <- combined.reports %>% select(language, total_files, db_total_files, fiction_files, db_fiction_files ,non.fiction_files, db_non_fiction_files, conversation_files, db_conversation_files, professional_files, db_professional_files, grammar_files, db_grammar_files, fiction_lines, db_fiction_lines, non.fiction_lines, db_non_fiction_lines, conversation_lines, db_conversation_lines, professional_lines, db_professional_lines, grammar_lines, db_grammar_lines, total_lines, db_total_lines, delta_total_lines)
```

```{r}
# Print
kable(combined.reports)
```

```{r}
# Write to CSV
write.csv(combined.reports, file="combined_reports-full.csv", quote=FALSE)
```

