---
title: "Identify which languages in TeDDi have multiple scripts"
author: "Steven Moran"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  github_document:
  pandoc_args: --webtex
---

```{r warning=FALSE, message=FALSE}
library(tidyverse)
library(knitr)
```

Load the R serialized version of the TeDDi database.

```{r}
# load('../../Database/test.RData') # for testing
load('../../Database/TeDDi.Rdata') # full database
```

Identify which languages have more than one writing system as indicated in their files.

```{r}
langs_ws <- clc_file %>% select(language_name_wals, writing_system) %>% group_by(language_name_wals, writing_system) %>% distinct()
langs_ws %>% group_by(language_name_wals) %>% filter(n() > 1) %>% kable()
```

Write all the languages and their writing systems to a table, so that we can use it in other reports, such as [creating maps](../maps/maps.md).

```{r}
langs_ws <- clc_file %>% select(language_name_wals, iso639_3, writing_system) %>% group_by(language_name_wals, writing_system) %>% distinct()
write_csv(langs_ws, 'TeDDi_writing_systems.csv')
```

