---
title: "Generate word frequency counts per file"
author: "Steven Moran"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  github_document:
  pandoc_args: --webtex
---

Load the `clc` package R library (named this because R package names cannot start with numbers). 

TODO: work in progress.


```{r}
library(clc)
library(readr)
```

Get a list of file IDs from the TeDDi database.

```{r}
file_ids <- clc::get_file_ids()
```

Here's an example of how to get the word count frequencies for one file.

```{r}
# Get the word frequency counts
df <- clc::get_word_counts(file_ids[1])
# Look up the file name
filename <- clc::clc_file %>% filter(id == file_ids[1]) %>% select(filename)
# Strip its extension
filename <- sub('\\.txt$', '', filename)
# Write the results to CSV
readr::write_csv(df, paste0('csv/', filename, '_freq.csv'))
```

Loop through the file IDs, generate word frequency counts per file, write the output to disk.

```{r echo=TRUE, results='hide'}
lapply(file_ids, function(i){
  df <- clc::get_word_counts(file_ids[i])
  filename <- clc::clc_file %>% filter(id == file_ids[i]) %>% select(filename)
  filename <- sub('\\.txt$', '', filename) 
  readr::write_csv(df, paste0('csv/', filename, '_freq.csv'))
})
```

Here's an example of the output.

```{r}
library(knitr)
df %>% head(n=50) %>% kable()
```
